"""thumb1

Revision ID: d13008afe7b3
Revises: bb12e0ddc3ae
Create Date: 2017-06-26 16:02:13.747811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13008afe7b3'
down_revision = 'bb12e0ddc3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumb_counts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumb_counts')
    # ### end Alembic commands ###
