"""thumbs

Revision ID: e1dd4d72b593
Revises: 9dccc8f6ddcb
Create Date: 2017-06-26 15:48:01.921641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1dd4d72b593'
down_revision = '9dccc8f6ddcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumb_counts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumb_counts')
    # ### end Alembic commands ###
